# Generated by Django 5.2.1 on 2025-05-14 21:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_event', models.CharField(db_index=True, max_length=255)),
                ('generated_text', models.TextField(db_index=True)),
                ('confidence_score', models.FloatField(db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ai_model_version', models.CharField(db_index=True, default='GPT-4', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, db_index=True, null=True)),
                ('comment', models.TextField(blank=True, db_index=True, null=True)),
                ('is_accurate', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='client.prediction')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, db_index=True, default='default.png', null=True, upload_to='profile-pictures')),
                ('location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('last_modified', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('verification_status', models.BooleanField(db_index=True, default=False)),
                ('notification_status', models.BooleanField(db_index=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('report_type', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('status', models.CharField(db_index=True, max_length=255)),
                ('sensor_data', models.JSONField(blank=True, db_index=True, default=dict, null=True)),
                ('verification_status', models.BooleanField(db_index=True, default=False)),
                ('rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prediction',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='client.report'),
        ),
    ]
