# Generated by Django 5.2.1 on 2025-05-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='client.report'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_accurate',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='client.prediction'),
        ),
    ]
