# Generated by Django 5.2.1 on 2025-05-25 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_feedback_report_alter_feedback_is_accurate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='parent_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='client.feedback'),
        ),
    ]
