# Generated by Django 5.1.7 on 2025-04-01 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_prediction_user_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='report',
            name='sensor_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
