# Generated by Django 5.1.7 on 2025-04-01 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_accurate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='ai_model_version',
            field=models.CharField(db_index=True, default='GPT-4', max_length=255),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='confidence_score',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='generated_text',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='predicted_event',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='valid_until',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, db_index=True, default='default.png', null=True, upload_to='profile-pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='report',
            name='rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='sensor_data',
            field=models.JSONField(blank=True, db_index=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='verification_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
