# Generated by Django 5.1.7 on 2025-04-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_prediction_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
